//! Disaster recovery primitives for state snapshot and rollback support.
//!
//! This module provides shared types and utilities for implementing
//! comprehensive disaster recovery capabilities across key contracts.
//!
//! ## Architecture
//!
//! Each protected contract exposes three DR entry-points:
//!
//! * `snapshot_state(env, admin, snapshot_id)` — Serialises critical state
//!   to `DataKey::Snapshot(snapshot_id)` with accompanying `SnapshotMeta`.
//!   A rolling window of at most `MAX_SNAPSHOTS` (3) is retained; the oldest
//!   snapshot is automatically deleted when a 4th is created.
//!
//! * `verify_post_upgrade_state(env, snapshot_id) -> StateVerificationReport`
//!   — Field-level comparison of snapshot vs. current on-chain state.
//!
//! * `rollback_to_snapshot(env, proposal_id)` — Requires `EMERGENCY_THRESHOLD`
//!   (4) approvals from the registered emergency signers before restoring the
//!   pre-upgrade WASM hash and all snapshotted state records.
//!
//! ## Constants
//!
//! | Constant              | Value | Meaning                              |
//! |-----------------------|-------|--------------------------------------|
//! | `MAX_SNAPSHOTS`       | 3     | Rolling window size                  |
//! | `EMERGENCY_THRESHOLD` | 4     | Minimum approvals required           |
//! | `EMERGENCY_SIGNERS`   | 7     | Total emergency signer slots         |

use soroban_sdk::{contracttype, Address, BytesN, Env, Vec};

// ---------------------------------------------------------------------------
// Core metadata struct
// ---------------------------------------------------------------------------

/// Metadata stored alongside every snapshot (`DataKey::SnapshotMetadata(id)`).
///
/// # Fields
/// * `created_at`       — Unix timestamp (seconds) when the snapshot was taken.
/// * `block_height`     — Ledger sequence number at snapshot time.
/// * `contract_version` — SHA-256 hash of the current WASM binary.
/// * `admin`            — Address that authorised the snapshot.
/// * `checksum`         — SHA-256 digest of the serialised snapshot payload,
///                        used for tamper-evidence verification.
/// * `escrow_count`     — Number of records captured (0 for non-escrow contracts).
/// * `snapshot_index`   — Ordinal position in the rolling window (0, 1, or 2).
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SnapshotMeta {
    /// Unix timestamp when the snapshot was created.
    pub created_at: u64,
    /// Ledger block height at snapshot time.
    pub block_height: u32,
    /// SHA-256 hash of the current WASM binary at snapshot time.
    pub contract_version: BytesN<32>,
    /// Admin address that authorized the snapshot.
    pub admin: Address,
    /// SHA-256 checksum of the serialised snapshot data for integrity verification.
    pub checksum: BytesN<32>,
    /// Number of entity records (escrows, stakes, proposals) captured.
    pub record_count: u64,
    /// Position within the rolling 3-snapshot window (0, 1, or 2).
    pub snapshot_index: u32,
}

// ---------------------------------------------------------------------------
// Verification report
// ---------------------------------------------------------------------------

/// Report generated by `verify_post_upgrade_state`.
///
/// Returned to the caller so they can programmatically gate rollback decisions.
///
/// # Fields
/// * `fields_checked` — Total number of storage fields compared.
/// * `mismatches`     — Human-readable descriptions of every field that
///                      differs between the snapshot and current state.
///                      An empty `Vec` means the state is intact.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct StateVerificationReport {
    /// Total number of storage fields checked.
    pub fields_checked: u32,
    /// List of mismatch descriptions (empty = no corruption detected).
    pub mismatches: Vec<soroban_sdk::String>,
}

// ---------------------------------------------------------------------------
// Rollback proposal & approval
// ---------------------------------------------------------------------------

/// A pending rollback proposal awaiting 4-of-7 emergency multi-sig approval.
///
/// Lifecycle: `propose_rollback` → `approve_rollback` (×4) → `rollback_to_snapshot`.
///
/// # Fields
/// * `id`              — Unique auto-incremented proposal identifier.
/// * `snapshot_id`     — The snapshot to restore.
/// * `old_wasm_hash`   — WASM binary hash to re-install; must be pre-uploaded.
/// * `approval_count`  — Running tally of distinct signers who have approved.
/// * `executed`        — True once `rollback_to_snapshot` has been called.
/// * `created_at`      — Timestamp of proposal creation (seconds).
/// * `proposer`        — Address that opened the proposal.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RollbackProposal {
    /// Unique proposal identifier (auto-incremented).
    pub id: u32,
    /// Snapshot ID to restore.
    pub snapshot_id: u32,
    /// Pre-uploaded WASM hash to re-apply.
    pub old_wasm_hash: BytesN<32>,
    /// Number of approvals accumulated so far.
    pub approval_count: u32,
    /// True once the rollback has been executed.
    pub executed: bool,
    /// Unix timestamp when the proposal was created.
    pub created_at: u64,
    /// Address that proposed the rollback.
    pub proposer: Address,
}

/// Individual approval record kept per (proposal_id, signer) pair.
///
/// Stored separately so we can detect double-signing attempts in O(1).
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RollbackApproval {
    /// Snapshot ID being rolled back to.
    pub snapshot_id: u32,
    /// Target WASM hash to restore.
    pub target_wasm_hash: BytesN<32>,
    /// Number of approvals received (requires 4-of-7).
    pub approval_count: u32,
    /// Whether the rollback has been executed.
    pub executed: bool,
    /// Timestamp when the rollback proposal was created.
    pub created_at: u64,
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Maximum number of snapshots retained simultaneously.
/// When a 4th snapshot is created the oldest is automatically removed.
pub const MAX_SNAPSHOTS: u32 = 3;

/// Number of emergency signers required to authorise a rollback (4-of-7).
pub const EMERGENCY_THRESHOLD: u32 = 4;

/// Total number of emergency signer slots.
pub const EMERGENCY_SIGNERS: u32 = 7;

// ---------------------------------------------------------------------------
// Checksum helper
// ---------------------------------------------------------------------------

/// Compute a stable 32-byte checksum over a byte slice using `env.crypto().sha256`.
///
/// Used to bind a snapshot to its payload: any modification to the serialised
/// escrow/staking/governance data will produce a different checksum, making
/// tampering detectable in `verify_post_upgrade_state`.
///
/// # Arguments
/// * `env`   — The Soroban execution environment.
/// * `data`  — Raw bytes to hash (typically a serialised struct via `to_xdr`).
///
/// # Returns
/// A 32-byte `BytesN<32>` SHA-256 digest.
pub fn compute_checksum(env: &Env, data: &soroban_sdk::Bytes) -> BytesN<32> {
    env.crypto().sha256(data).into()
}

// ---------------------------------------------------------------------------
// Snapshot index management
// ---------------------------------------------------------------------------

/// Insert `snapshot_id` into the rolling index, pruning the oldest entry
/// when the window exceeds `MAX_SNAPSHOTS`.
///
/// Returns the snapshot ID that was evicted (if any) so the caller can
/// delete its `DataKey::Snapshot` and `DataKey::SnapshotMetadata` entries.
///
/// # Invariant
/// After this call `index.len() <= MAX_SNAPSHOTS`.
pub fn push_snapshot_index(index: &mut Vec<u32>, new_id: u32) -> Option<u32> {
    index.push_back(new_id);
    if index.len() > MAX_SNAPSHOTS {
        // Remove and return the front (oldest) entry
        Some(index.pop_front_unchecked())
    } else {
        None
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    extern crate std;

    use super::*;
    use soroban_sdk::{vec, Env};

    /// `push_snapshot_index` respects the MAX_SNAPSHOTS rolling window.
    #[test]
    fn test_push_snapshot_index_rolling() {
        let env = Env::default();
        let mut idx: Vec<u32> = vec![&env];

        // First three snapshots fit inside the window.
        assert_eq!(push_snapshot_index(&mut idx, 1), None);
        assert_eq!(push_snapshot_index(&mut idx, 2), None);
        assert_eq!(push_snapshot_index(&mut idx, 3), None);
        assert_eq!(idx.len(), 3);

        // Fourth snapshot evicts the oldest (id=1).
        let evicted = push_snapshot_index(&mut idx, 4);
        assert_eq!(evicted, Some(1));
        assert_eq!(idx.len(), 3);
        assert_eq!(idx.get(0).unwrap(), 2);
        assert_eq!(idx.get(2).unwrap(), 4);

        // Fifth evicts id=2.
        let evicted2 = push_snapshot_index(&mut idx, 5);
        assert_eq!(evicted2, Some(2));
        assert_eq!(idx.get(0).unwrap(), 3);
    }

    /// Checksum helper produces a non-zero 32-byte value for non-empty input.
    #[test]
    fn test_compute_checksum_non_zero() {
        let env = Env::default();
        let data = soroban_sdk::Bytes::from_slice(&env, b"hello world");
        let hash = compute_checksum(&env, &data);
        // SHA-256("hello world") is known; just check it's not all zeros.
        let all_zero = BytesN::<32>::from_array(&env, &[0u8; 32]);
        assert_ne!(hash, all_zero);
    }
}
