#!/usr/bin/env python3
"""
MentorMinds Audit Toolkit
Generates automated contract inventories, privileged function maps, 
event inventories, and storage schema maps for auditors.
"""

import os
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
CONTRACTS_DIRS = [PROJECT_ROOT / "contracts", PROJECT_ROOT / "escrow"]
OUTPUT_FILE = PROJECT_ROOT / "docs" / "AUDIT-INVENTORY-REPORT.md"

# Regex patterns for Soroban Rust traits
FN_PATTERN = re.compile(r'pub fn ([a-zA-Z0-9_]+)\s*\(')
AUTH_PATTERN = re.compile(r'([a-zA-Z0-9_]+)\.require_auth\(\)')
EVENT_PATTERN = re.compile(r'env\.events\(\)\.publish\(\s*\((.*?)\)')
STORAGE_PATTERN = re.compile(r'env\.storage\(\)\.(instance|persistent|temporary)\(\)\.(set|get|has)\((.*?)\)')

def scan_contracts():
    inventory = {}
    
    for d in CONTRACTS_DIRS:
        if not d.exists():
            continue
        for root, _, files in os.walk(d):
            for file in files:
                if file.endswith('.rs'):
                    filepath = Path(root) / file
                    with open(filepath, 'r', encoding='utf-8') as f:
                        content = f.read()
                        
                        # Identify functions
                        functions = FN_PATTERN.findall(content)
                        if not functions:
                            continue
                            
                        contract_name = filepath.parent.parent.name
                        if contract_name not in inventory:
                            inventory[contract_name] = {
                                'path': str(filepath.relative_to(PROJECT_ROOT)),
                                'functions': functions,
                                'auth_requires': AUTH_PATTERN.findall(content),
                                'events': EVENT_PATTERN.findall(content),
                                'storage': STORAGE_PATTERN.findall(content)
                            }
    return inventory

def generate_markdown_report(inventory):
    lines = [
        "# 🛡️ Automated Audit Inventory Report",
        "**Generated by**: `scripts/audit_toolkit.py`\n",
        "This report maps out the contract inventory, privileged functions, storage usage, and events to streamline external security audits.\n",
        "---"
    ]
    
    for contract, data in inventory.items():
        lines.append(f"## Contract: `{contract}`")
        lines.append(f"**Path**: `{data['path']}`\n")
        
        # 1. Contract Inventory (Functions)
        lines.append("### Public Functions")
        if data['functions']:
            for fn in data['functions']:
                lines.append(f"- `{fn}`")
        else:
            lines.append("*No public functions found.*")
        lines.append("")
        
        # 2. Privileged Function Mapping
        lines.append("### Privileged Operations (`require_auth`)")
        if data['auth_requires']:
            unique_auths = set(data['auth_requires'])
            for auth in unique_auths:
                lines.append(f"- Requires authorization from: `{auth}`")
        else:
            lines.append("*No specific authorization bounds found in this file.*")
        lines.append("")
        
        # 3. Storage Schema Mapping
        lines.append("### Storage Schema Map")
        if data['storage']:
            lines.append("| Storage Tier | Operation | Key Reference |")
            lines.append("|--------------|-----------|---------------|")
            for tier, op, key in data['storage']:
                clean_key = key.split(',')[0].strip().replace('&', '')
                lines.append(f"| `{tier}` | `{op}` | `{clean_key}` |")
        else:
            lines.append("*No direct storage access patterns matched.*")
        lines.append("")
        
        # 4. Event Inventory
        lines.append("### Event Inventory")
        if data['events']:
            for ev in data['events']:
                # Clean up the tuple match
                clean_ev = ev.replace('\n', ' ').strip()
                lines.append(f"- Topic signature: `{clean_ev}`")
        else:
            lines.append("*No event publications found.*")
        lines.append("\n---")
        
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
        
    print(f"✅ Audit inventory report generated successfully at {OUTPUT_FILE}")

if __name__ == "__main__":
    print("Scanning contracts and generating inventory...")
    inventory_data = scan_contracts()
    generate_markdown_report(inventory_data)